site_name: DetectMate Service
site_url: https://ait-detectmate.github.io/DetectMateService/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Configuration: configuration.md
    - Usage:
      - Quick Start: usage.md
      - Using a Library Component: library.md
      - Running a Pipeline: pipeline.md
