component_type: "detectors.new_value_detector.NewValueDetector"
component_config_class: "detectors.new_value_detector.NewValueDetectorConfig"
component_name: "test-nvd"
manager_addr: "ipc:///tmp/test_nvd_cmd.ipc"
engine_addr: "ipc:///tmp/test_nvd_engine.ipc"

log_level: "DEBUG"
log_dir: "./logs"
log_to_console: true
log_to_file: false
engine_autostart: true
