component_type: "parsers.template_matcher.MatcherParser"
component_config_class: "parsers.template_matcher.MatcherParserConfig"
component_name: "test-parser"
manager_addr: "ipc:///tmp/test_parser_cmd.ipc"
engine_addr: "ipc:///tmp/test_parser_engine.ipc"
output_engine_addr: "ipc:///tmp/test_nvd_engine.ipc"
log_level: "DEBUG"
log_dir: "./logs"
log_to_console: true
log_to_file: false
engine_autostart: true
